server:
  port: 8086
spring:
  application:
    name: user-manager
  profiles:
    include: local, default
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER}
          jwk-set-uri: ${KEYCLOAK_JWKS}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid)}
    hostname: ${USER_MANAGER_DOMAIN_NAME}
    nonSecurePort: 80
  client:
    service-url:
      defaultZone: ${EUREKA_URL}/eureka/
  password: ${EUREKA_USER_PASSWORD}
security:
  user:
    password: ${eureka.password}

management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  swagger-ui:
    operations-sorter: method
keycloak-client:
  url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  auth-url: ${KEYCLOAK_AUTH_URL}
aws:
  region: ${AWS_REGION}
  bucket: ${AWS_BUCKET_NAME}
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  endpoint: ${AWS_ENDPOINT}
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  public-key: ${STRIPE_PUBLIC_KEY}
