server:
  port: 8086
spring:
  application:
    name: user-manager
  profiles:
    include: local, default
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid)}
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka