# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout main branch 
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: temurin
        cache: maven
    
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Step 4 - Check target folder -
      run: |
        cd target
        ls -a
      
    
