# This is a basic workflow to help you get started with Actions

name: "PR Title Check"

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  # This workflow contains a single job called "build"
  pr-title-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v1
        with:
          # Match pull request titles in the form UI-1234 - Message.
          pattern: '\w{5,}'
     
